### PR TITLE
added missing api parameters

### PR DESCRIPTION
**Pull request by abdulsuhail**

### CODE REVIEW

**Comment by abdulsuhail** [comment]
@tkadlec added documentation for the recently added parameters, please review

**Comment by tkadlec** [comment]
@abdulsuhail Looks like we also need them documented here: https://github.com/marcelduran/webpagetest-api/blob/7102af71c6865c5efe85fab22b92f9dbe417c689/README.md#test-works-for-runtest-method-only

**Comment by tkadlec** [comment]
_almost there_. :)

Can you update the author, homepage, repo and bugs info in the package.json as well?

**Comment by tkadlec** [comment]
Nice work @abdulsuhail !

**Pull request merged**
